### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by newyork-anthonyng** [visortelle/react-sticky-node#1]
I think an example that shows how `react-sticky-node` works would be helpful for new users. 

I could create one using `CodeSandbox.io` and submit a PR; unless you have other suggestions?

**Comment by visortelle** [comment]
I participate in this project development 
https://github.com/OpusCapitaBES/js-react-showroom-client
It is a sandbox and documenting tool for react components.
I'd rather make examples and documentation like here https://opuscapita.github.io/react-dates

**Comment by visortelle** [comment]
### This project is deprecated! 
### Please use `StickyNode` component from https://github.com/OpusCapita/react-overlays/
