### ISSUE TITLE
Calculation of getBoundingClientRect isn't accurate

### ISSUE THREAD

**Issue by newyork-anthonyng** [visortelle/react-sticky-node#2]
See this [example](https://codesandbox.io/s/98O6GGP0Y).

Notice how the sticky element "sticks" too late. This is because the `getBoundingClientRect` calculation is incorrect. It doesn't take into account the height of the `Hello World` header.

**Comment by visortelle** [comment]
### This project is deprecated! 
### Please use `StickyNode` component from https://github.com/OpusCapita/react-overlays/
